from pydantic import BaseModel
import datetime
class Token(BaseModel):
    id: str 
    is_admin: str
    exp: datetime.datetime
class StudentSignUpData(BaseModel):
    user_name: str
    name: str
    password: str
class TeacherLoginData(BaseModel):
    user_name: str 
    password: str
    admin_code: str
class TeacherSignUpData(BaseModel):
    name: str
    user_name: str 
    password: str
    admin_code: str
class LogInUser(BaseModel):
    user_name: str 
    password: str
class Task(BaseModel):
    name: str
    number: str
    diff: str 
    text: str 
    answer: str 
    description: str
class AiSchema(BaseModel):
    code: str
    task: str
    comment: str
